spring:
  application:
    name: "book-store-back"

  profiles:
    active: dev

  # DataSource 설정
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/be6_5ritang
    username: be6_5ritang
    password: j2EqdFa0rt.tX]WK
    driver-class-name: com.mysql.cj.jdbc.Driver

