server:
  port: 8083
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8

spring:
  application:
    name: "book-store-back"

  profiles:
    active: dev

  jwt:
    secret: 33085d3cf14717d13f122979944e1e886636cc19e0f749dfbce423bb0031beae8b8758243ce109259c32a83a9325ef2c64433bc0339321d9540036a11884f8fc
    access-token:
      expires-in: 600000
    refresh-token:
      expires-in: 86400000

  mail:
    host: smtp.gmail.com
    port: 587
    username: monte61984@gmail.com
    password: vbtzvwxzyzlscamv
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

nhncloud:
  appkey: vyiy4M85i8mJ5mgP
  secretkey: fBlt6m4cSRJs07X05mhPBfmofWoBlcSU

naver:
  client:
    id: FqTcItBuNIlp3v3oMKdQ
    secret: WQxeHO8nj5

springdoc:
  api-docs:
    path: /back-api
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /back-api.html
    disable-swagger-default-url: true

logging:
  file:
    path: ./logs

  level:
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR

oritang:
  mysql:
    url: 073309ef26b34581afc19feb7720380e
    username: 7d697c13adf84236b7ca5ea60870ff9c
    password: 4766eb1428334444b8a10ce26bd980e8
  
  redis:
    host: 4c4a07c6d57c41cba23cf12de6c87559
    port: 0de6a31493de4282830c2dab83e7264c
    password: d9b767e1131b4434b75d1fb52444ee1e
    database: d5311ac7b1164c6ea75202fc8d14085f
