### 배달 정책 추가
POST localhost:8080/deliveries-policies
Content-Type: application/json

{
  "deliveryPolicyName": "기본 배송비",
  "deliveryPolicyContent": "주문 금액이 5만원 이하",
  "deliveryPolicyPrice": 3000.00
}

### 특정 배달 정책 가져오기
GET localhost:8080/deliveries-policies/1
Content-Type: application/json

### 배달 정책 업데이트
PUT localhost:8080/deliveries-policies/1
Content-Type: application/json

{
  "deliveryPolicyName": "기본 배송비",
  "deliveryPolicyContent": "주문 금액이 5만원 이하",
  "deliveryPolicyPrice": 5000.00
}

### 배달 정책 삭제
DELETE localhost:8080/deliveries-policies/1
Content-Type: application/json

### 모든 배달 정책 가져오기
GET localhost:8080/deliveries-policies
Content-Type: application/json



