
### 위시리스트 추가
POST localhost:8080/wishLists
Content-Type: application/json

{
  "bookId": 126,
  "userId": 1
}

### 위시리스트 삭제
DELETE localhost:8080/wishLists/1
Content-Type: application/json

### 모든 위시리스트 가져오기
GET localhost:8080/wishLists
Content-Type: application/json

{
  "userId": 1
}



